In [1]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

In [2]:
lib = np.load("pca.npz")
data = lib["data"]
labels = lib["labels"]

data_means = np.mean(data, axis=0)
norm_data = data - data_means
_, _, Vh = np.linalg.svd(norm_data)
pca_data = np.matmul(norm_data, Vh[:3].T)


In [6]:
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
data.shape, labels.shape

((150, 4), (150,))

In [11]:
data_means

array([5.8433347, 3.054    , 3.7586665, 1.1986669], dtype=float32)

In [12]:
norm_data

array([[-7.4333477e-01,  4.4600010e-01, -2.3586664e+00, -9.9866694e-01],
       [-9.4333458e-01, -5.3999901e-02, -2.3586664e+00, -9.9866694e-01],
       [-1.1433349e+00,  1.4600015e-01, -2.4586666e+00, -9.9866694e-01],
       [-1.2433348e+00,  4.6000004e-02, -2.2586665e+00, -9.9866694e-01],
       [-8.4333467e-01,  5.4600000e-01, -2.3586664e+00, -9.9866694e-01],
       [-4.4333458e-01,  8.4600019e-01, -2.0586665e+00, -7.9866695e-01],
       [-1.2433348e+00,  3.4600019e-01, -2.3586664e+00, -8.9866692e-01],
       [-8.4333467e-01,  3.4600019e-01, -2.2586665e+00, -9.9866694e-01],
       [-1.4433346e+00, -1.5399981e-01, -2.3586664e+00, -9.9866694e-01],
       [-9.4333458e-01,  4.6000004e-02, -2.2586665e+00, -1.0986669e+00],
       [-4.4333458e-01,  6.4600015e-01, -2.2586665e+00, -9.9866694e-01],
       [-1.0433345e+00,  3.4600019e-01, -2.1586666e+00, -9.9866694e-01],
       [-1.0433345e+00, -5.3999901e-02, -2.3586664e+00, -1.0986669e+00],
       [-1.5433345e+00, -5.3999901e-02, -2.6586666e

In [13]:
_

array([25.089865 ,  6.0078526,  3.4205353,  1.8785024], dtype=float32)

In [14]:
_

array([25.089865 ,  6.0078526,  3.4205353,  1.8785024], dtype=float32)

In [15]:
Vh

array([[ 0.36158967, -0.08226889,  0.8565721 ,  0.35884392],
       [-0.65653986, -0.72971237,  0.17576739,  0.07470647],
       [ 0.5809973 , -0.5964181 , -0.07252406, -0.54906094],
       [ 0.31725457, -0.32409436, -0.47971898,  0.75112057]],
      dtype=float32)

In [16]:
pca_data

array([[-2.6842074 , -0.3266064 ,  0.02151108],
       [-2.715391  ,  0.16955759,  0.20352077],
       [-2.88982   ,  0.13734652, -0.02471012],
       [-2.7464375 ,  0.31112528, -0.0376727 ],
       [-2.7285933 , -0.3339237 , -0.09623039],
       [-2.2798977 , -0.747782  , -0.17432633],
       [-2.8208911 ,  0.08210534, -0.26425192],
       [-2.6264825 , -0.17040463,  0.01580077],
       [-2.887959  ,  0.57079875, -0.02733612],
       [-2.673845  ,  0.10669251,  0.19153267],
       [-2.5065272 , -0.65193427,  0.06927431],
       [-2.6131432 , -0.02152006, -0.107651  ],
       [-2.7874343 ,  0.22774087,  0.20032716],
       [-3.225201  ,  0.50328064, -0.06841427],
       [-2.6435435 , -1.1861942 ,  0.14450508],
       [-2.38387   , -1.3447534 , -0.2837315 ],
       [-2.6225266 , -0.81808895, -0.14531669],
       [-2.648323  , -0.31913576, -0.03339502],
       [-2.1990786 , -0.8792431 ,  0.11452064],
       [-2.5873466 , -0.5204727 , -0.21957281],
       [-2.310532  , -0.39786714,  0.233

In [23]:
pca_data[:, 2]

array([ 0.02151108,  0.20352077, -0.02471012, -0.0376727 , -0.09623039,
       -0.17432633, -0.26425192,  0.01580077, -0.02733612,  0.19153267,
        0.06927431, -0.107651  ,  0.20032716, -0.06841427,  0.14450508,
       -0.2837315 , -0.14531669, -0.03339502,  0.11452064, -0.21957281,
        0.23369485, -0.21483716, -0.29961973, -0.04568082, -0.12940824,
        0.24711561, -0.10126379,  0.07235831,  0.13925248, -0.0464673 ,
        0.07127452,  0.13838753, -0.23058641, -0.16358244,  0.19153267,
        0.15684158,  0.26116246,  0.19153267, -0.07972544,  0.0739004 ,
       -0.08424231,  0.34096074, -0.19900912, -0.27071777, -0.30348852,
        0.09051499, -0.1719191 , -0.0900622 ,  0.01117462,  0.08269507,
        0.40612885,  0.01712923,  0.3382601 ,  0.1770822 ,  0.30654383,
       -0.04118952, -0.17002308, -0.01567293,  0.41481376, -0.2834381 ,
        0.26648927, -0.13232854,  0.69194084,  0.06215665, -0.09365943,
        0.31322864, -0.32838506,  0.27028006,  0.49734765,  0.23

In [24]:
pca_data.shape

(150, 3)

In [25]:
print(pca_data)

[[-2.6842074  -0.3266064   0.02151108]
 [-2.715391    0.16955759  0.20352077]
 [-2.88982     0.13734652 -0.02471012]
 [-2.7464375   0.31112528 -0.0376727 ]
 [-2.7285933  -0.3339237  -0.09623039]
 [-2.2798977  -0.747782   -0.17432633]
 [-2.8208911   0.08210534 -0.26425192]
 [-2.6264825  -0.17040463  0.01580077]
 [-2.887959    0.57079875 -0.02733612]
 [-2.673845    0.10669251  0.19153267]
 [-2.5065272  -0.65193427  0.06927431]
 [-2.6131432  -0.02152006 -0.107651  ]
 [-2.7874343   0.22774087  0.20032716]
 [-3.225201    0.50328064 -0.06841427]
 [-2.6435435  -1.1861942   0.14450508]
 [-2.38387    -1.3447534  -0.2837315 ]
 [-2.6225266  -0.81808895 -0.14531669]
 [-2.648323   -0.31913576 -0.03339502]
 [-2.1990786  -0.8792431   0.11452064]
 [-2.5873466  -0.5204727  -0.21957281]
 [-2.310532   -0.39786714  0.23369485]
 [-2.5432353  -0.4400309  -0.21483716]
 [-3.2158582  -0.1416146  -0.29961973]
 [-2.303129   -0.10552175 -0.04568082]
 [-2.3561716   0.03121017 -0.12940824]
 [-2.507918    0.13905711

In [27]:
pca_data[148]

array([ 1.9016286 , -0.11587591, -0.7228744 ], dtype=float32)