## Slice like a ninja

In [58]:
import numpy as np

In [59]:
mat1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [60]:
mat2 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
                 [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],
                 [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]])

In [61]:
# Data about the matrix
print("size: {}, dimensions: {}, type: {}, shape: {}".format(mat1.size, mat1.ndim, type(mat1), mat1.shape))

size: 10, dimensions: 2, type: <class 'numpy.ndarray'>, shape: (2, 5)


In [62]:
axes={1: (1, 3)}
len(axes)

1

In [63]:
def np_slice(matrix, axes={}):
    """ slice a matrix """
    for key, val in axes.items():
        return matrix[:,val[0]:val[1]]

In [64]:
print(np_slice(mat1, axes={1: (1, 3)}))

[[2 3]
 [7 8]]


In [65]:
print(np_slice(mat1, axes={1: (1, None)}))

[[ 2  3  4  5]
 [ 7  8  9 10]]


In [66]:
mat1.take(range(1,), 1)

array([[1],
       [6]])

In [74]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [76]:
x = x.reshape(2,3,1)

In [77]:
x

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [78]:
x.shape

(2, 3, 1)

In [79]:
x[1:10:5]

array([[[4],
        [5],
        [6]]])

In [80]:
x[1:10:5, ::-1]

array([[[6],
        [5],
        [4]]])

In [81]:
obj = (slice(1,10,5), slice(None, None, -1))

In [82]:
x[obj]

array([[[6],
        [5],
        [4]]])