## Slice like a ninja

In [164]:
import numpy as np

In [165]:
matrix = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [166]:
mat2 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]],
                 [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]],
                 [[21, 22, 23, 24, 25], [26, 27, 28, 29, 30]]])

In [167]:
# Data about the matrix
print("size: {}, dimensions: {}, type: {}, shape: {}".format(mat1.size, mat1.ndim, type(mat1), mat1.shape))

size: 10, dimensions: 2, type: <class 'numpy.ndarray'>, shape: (2, 5)


In [168]:
axes={1: (1, 3)}
len(axes)

1

In [169]:
def np_slice(matrix, axes={}):
    """ slice a matrix """
    for key, val in axes.items():
        return matrix[:,val[0]:val[1]]

In [170]:
print(np_slice(mat1, axes={1: (1, 3)}))

[[2 3]
 [7 8]]


In [171]:
matrix[0]

array([1, 2, 3, 4, 5])

In [172]:
matrix[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [173]:
matrix[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [183]:
matrix[:,0:4:2]

array([[1, 3],
       [6, 8]])