In [2]:
import numpy as np

In [3]:
mat1 = np.array(
                [
                    [1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10]
                    ])

In [4]:
# axes={1: (1, 3)}
# ndarray.take(indices, axis=None, out=None, mode='raise')
mat1.take(range(1,3), 1)

array([[2, 3],
       [7, 8]])

In [5]:
# axes={0: (2,), 2: (None, None, -2)}
mat2 = np.array(
                [
                    [
                        [1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10]
                    ],
                    [
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20]
                    ],
                    [
                        [21, 22, 23, 24, 25],
                        [26, 27, 28, 29, 30]
                    ]
                ])

In [6]:
a = np.arange(24).reshape(2,3,4)

In [7]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
x = np.arange(10)

In [9]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
x[2]

2

In [11]:
x.shape = (2,5)

In [12]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
x[1]

array([5, 6, 7, 8, 9])

In [14]:
mat1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
axes={1: (1, 3)}

In [17]:
axes

{1: (1, 3)}

In [57]:
axes.items()

dict_items([(1, (1, 3))])

In [34]:
slice_obj

[slice(1, 1, 3)]

In [46]:
mat1[:,1:3:]

array([[2, 3],
       [7, 8]])

In [50]:
mat1[...]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [54]:
mat1[..., 1:3]

array([[2, 3],
       [7, 8]])

In [82]:
slice_obj = [slice(None)] *(max(axes)+1)
for key, val in axes.items():
    slice_obj[key] = slice(*val)
mat1[tuple(slice_obj)]

array([[2, 3],
       [7, 8]])

In [83]:
slice_obj

[slice(None, None, None), slice(1, 3, None)]

In [86]:
mat2 = np.array(
                [
                    [
                        [1, 2, 3, 4, 5],
                        [6, 7, 8, 9, 10]
                    ],
                    [
                        [11, 12, 13, 14, 15],
                        [16, 17, 18, 19, 20]
                    ],
                    [
                        [21, 22, 23, 24, 25],
                        [26, 27, 28, 29, 30]
                    ]
                ])
axes={0: (2,), 2: (None, None, -2)}

In [90]:
slice_obj = [slice(None)] *(max(axes)+1)
for key, val in axes.items():
    print(val)
    slice_obj[key] = slice(* val)
mat2[tuple(slice_obj)]

(2,)
(None, None, -2)


array([[[ 5,  3,  1],
        [10,  8,  6]],

       [[15, 13, 11],
        [20, 18, 16]]])